baseURL = '/'
languageCode = 'en-us'
title = 'Jerome Chua'
author = 'Jerome Chua'
name = 'Jerome Chua'
theme = 'paper'

[pagination]
  pagerSize = 4

[params]
  color = 'linen'
  twitter = 'jeromechuame'
  github = 'jerome-chua'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"