baseURL = 'https://jeromechua.pages.dev'
name = 'Jerome Chua'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'paper'
color = 'linen' 
twitter = 'jeromechuame'
github = 'jerome-chua'
linkedin = 'jeromechua'